# --- FAZA 1: BUDOWANIE (Instalacja zależności) ---
FROM python:3.11-slim as builder
WORKDIR /app
ENV PYTHONUNBUFFERED 1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- FAZA 2: URUCHAMIANIE ---
FROM builder as final
COPY . .

# ZMIANA: Zamiast uruchamiać serwer, pokaż nam, jakie pliki są w katalogu /app
CMD ["find", ".", "-maxdepth", "3", "-not", "-path", "*/.*"]
